### ISSUE TITLE
xsel not working when executed using double click

### ISSUE THREAD

**Issue by potholiday** [kfish/xsel#11]
Some how `xsel` not working when i executed the bash script using double click. If executed from command line the below script is working

```
#!/bin/bash
clpy=$(xsel -p);
echo $clpy
read -p "Press any key to continue... " -n1 -s
```

Any idea whats happening

**Comment by kfish** [comment]
Sorry for not replying when you posted this. I guess the output of xsel was getting written to the stdout of whatever process is handling your double clicks (eg. your window manager or application launcher).
