### ISSUE TITLE
Why maximum 4000 characters output with xsel -b ?

### ISSUE THREAD

**Issue by cirosantilli** [kfish/xsel#13]
When I compile from source at https://github.com/kfish/xsel/tree/9674445d8ea9f60f4d1a154be6fdb12e7af8f0c6 and do:

```
seq 10000  | ./xsel -b
./xsel -b | wc
```

The output contains only the first 4k characters.

On the other hand, if I do ctrl + v on GUI apps like Firefox, I get all the characters.

Why this limitation? I saw the 4000 constant in the source:

```
max_req = 4000;
```

but wasn't patient enough to deduce the rest :-)

Why not increase that limit a bit more?

Ubuntu 14.04.

**Comment by ebiggers** [comment]
I posted a fix for this: https://github.com/kfish/xsel/pull/16.  I'm not sure this project has an active maintainer though.

**Comment by kfish** [comment]
This was fixed by #16
