### ISSUE TITLE
Fails to Read Standard Input

### ISSUE THREAD

**Issue by baskerville** [kfish/xsel#2]
I stumbled upon the following (requires `dash`, [reproduce_links](https://github.com/baskerville/bin/blob/master/reproduce_links) and [link_command](https://github.com/baskerville/bin/blob/master/link_command)):

```
reproduce_links | xsel -i
```

results in:

```
xsel -o
```

being empty, while `xclip` works as expected (with the same parameters).

Also, doing:

```
reproduce_links | xsel -f
```

just after the first command generates a segfaults.

**Comment by kfish** [comment]
I expect this was fixed with changes to large transfer INCR handling during the past few years. Please re-open if this still does not work with current master.
