### ISSUE TITLE
Install on Ubuntu

### ISSUE THREAD

**Issue by ElijahLynn** [kfish/xsel#23]
Reading through the install instructions here, https://github.com/kfish/xsel/blob/master/INSTALL.md, and it is implying that configure and configure.in should exist. They don't exist so consider this issue me brain dumping how to get it installed on Ubuntu.

**Comment by kfish** [comment]
Hi, apologies for the delay in replying.

These are included in a source tarball. Unfortunately the last time I made a source tarball was the 1.2.0 release 10 years ago. It's probably about time for an update.

To generate configure.in, and then configure, you need to install the autotools-dev package, and run:

automake -a
autoconf

(This applies to any package using the ancient automake/autoconf toolchain :)

**Comment by skierpage** [comment]
This bug is not closed, there is still an INSTALL.md with faulty instructions. Please reopen.
