### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by avg-I** [kfish/xsel#28]
Can a new release please be done?
For the sake of all fixes that have accumulated since 1.2.0.
Thank you.

**Comment by ThisGuyCodes** [comment]
:+1: in particular I'm interested in seeing https://github.com/kfish/xsel/pull/16 in the wild

**Comment by wchargin** [comment]
The most recent release appears to have been just over ten years ago, so
I don’t have high hopes, but I would also love to see a release with #16
(especially into Debian/Ubuntu’s repos).

**Comment by kfish** [comment]
Yes I'm pretty keen to get those fixes out too. I guess the best way to do that now is to use github for everything rather than my personal site.

**Comment by noahfx** [comment]
Hi @wchargin, 
I have prepared and uploaded a new Debian package release[1] with the latest changes, including #16

[1]: https://tracker.debian.org/news/964383/accepted-xsel-120git9bfc13d20180109-1-source-amd64-into-unstable/

**Comment by noahfx** [comment]
hi @wschlich 
Some months ago I did upload xsel with the latest changes at Master to Debianm. if I am not 
wrong this version is included in Ubuntu 18.10.
I'm not sure which Ubuntu version are you running, but if you are using the latest one let me know if 
you still have the issue
Regards

**Comment by ThisGuyCodes** [comment]
@noahfx I'm on Ubuntu 18.10, can confirm the latest version in apt is `1.2.0+git9bfc13d.20180109-1`, which is fairly unambiguously the latest from this repo.

**Comment by wschlich** [comment]
@noahfx
> hi @wschlich
> Some months ago I did upload xsel with the latest changes at Master to Debian. if I am not
> wrong this version is included in Ubuntu 18.10.
> I'm not sure which Ubuntu version are you running, but if you are using the latest one let me know if
> you still have the issue

I'm not running any version of Ubuntu ;-)

@kfish Considering a new release anytime soon?

**Comment by Arkanosis** [comment]
FYI, [I've asked for the Ubuntu 18.04 LTS package to be updated](https://bugs.launchpad.net/ubuntu/+source/xsel/+bug/1818695) to 1.2.0+git9bfc13d.20180109 as well.

The xsel release on Ubuntu 18.04 LTS (1.2.0) exhibits some data corruption at byte 7624 (not at byte 7623, not at byte 7625) that the xsel release on Ubuntu 18.10 (1.2.0+git9bfc13d.20180109) doesn't:

  $ printf '%7624s' | xsel ; xsel | hexdump
  0000000 2020 2020 2020 2020 2020 2020 2020 2020                                                                                                                                                                                                                                 
  *                                                                                                                                                                                                                                                                               
  0001dc0 2020 2020 2020 2020 **0fd1**                                                                                                                                                                                                                                                
  0001dca

**Comment by marv** [comment]
What's the status of this? I'd love to see a new release too :-)

**Comment by ganwell** [comment]
I wanted to update xsel in my distro and [they are asking]( https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7983) if I can get upstream to make a new release.

1.2.0 is seriously broken.

**Comment by astier** [comment]
Its time for the annual request to ask for a new release. Thank you.

**Comment by anthraxx** [comment]
@kfish can you pleeease git tag a new release.

**Comment by ferki** [comment]
Thank you @kfish for releasing 1.2.1! :tada: 

This issue may be closed now.

**Comment by Arkanosis** [comment]
Thank you @kfish ! :heart:
