### ISSUE TITLE
timeout does not work as expected

### ISSUE THREAD

**Issue by oz123** [kfish/xsel#3]
Hi, 

I tried earasing the clipboard with -t 3000. If I understand the English correctly in the man page, this means that after 3 seconds the clip board selection will expire?
Any I tried this:

```
[60] oz123@yenitiny:~/software/xsel-1.2.0 $ echo "test" | ./xsel -p -i   --selectionTimeout 3 && sleep 3 && xsel
test
[61] oz123@yenitiny:~/software/xsel-1.2.0 $ 
```

As you can see, the selection is still there after the timeout ...

I would appreciate it if you can comment about it. 
Also I read the C code,  and I saw this:

```
     2082   timeout = timeout_ms * 1000;
```

The value read from command line is multplied by 1000, so I think the manual page should be updated  ... The timeout value read is in Seconds.

**Comment by kfish** [comment]
This was fixed by #5
