### ISSUE TITLE
support remove last newline

### ISSUE THREAD

**Issue by roachsinai** [kfish/xsel#38]
`xsel --clipboard` will always get a newline, any plan to add a option to remove it.

**Comment by aaaaaaaalex** [comment]
would also love this - there are numerous stackoverflow questions (with very bad answers)  asking how to work around this

**Comment by aaaaaaaalex** [comment]
Created a pull request (https://github.com/kfish/xsel/pull/39) for this just now :smile:

**Comment by kfish** [comment]
Fixed in #39, included in release 1.2.1
