### ISSUE TITLE
Portability issues to 64-bit systems

### ISSUE THREAD

**Issue by mdempsky** [kfish/xsel#4]
XGetWindowProperty and XChangeProperty are defined as using arrays of "long" when format==32, even on 64-bit systems where "long" is a 64-bit type.  However, xsel.c uses "int" for format==32.  OpenBSD's now including this patch for xsel in its ports tree to fix problems on LP64 platforms: http://www.openbsd.org/cgi-bin/cvsweb/ports/x11/xsel/patches/patch-xsel_c

**Comment by kfish** [comment]
Applied in commit 3254b78
