### ISSUE TITLE
Why xsel doesnt update the selection output when I'm selecting nothing?

### ISSUE THREAD

**Issue by seujorgenochurras** [kfish/xsel#54]
I'm not sure if I understood it right, but why xsel doesnt display nothing when I'm not selecting? 
Instead it displays the last thing I selected

**Comment by kfish** [comment]
I think that's just how X selection works, whichever app is the current selection owner will answer requests for the selected text.

**Comment by Furlanetto-Dev** [comment]
I don't even remember why I needed this lol
