### ISSUE TITLE
Copying vim clipboard

### ISSUE THREAD

**Issue by fmoralesc** [kfish/xsel#7]
At [neovim](https://github.com/neovim/neovim), we are working on a modernization/refactor of vim. One of the things we have done so far is removing all X dependencies from the codebase, which meant getting rid of the clipboard code. It wasn't observed at the time that vim uses a custom target to signal that the copied text is copied character-wise (as a blob), line-wise (as a set of lines) or block wise (as a visual block). This meant that copying and pasting blocks of text treated it as regular text, causing the wrong thing tho happen (more details at https://github.com/neovim/neovim/issues/1822). We currently use `xsel` when available to copy the data, but it seems that it drops the custom target, and it has no way to make it add it optionally.

vim uses a couple of targets, `_VIM_TEXT` and `_VIMENC_TEXT`, to signal this. Depending on the copy mode, it will append the data with `\x00` (regualr) or `\x02` (block), and in the case of `_VIMENC_TEXT` with `\x0[02]encoding\x00` (i.e, `\x02utf-8\x00`).

We've tried to fix this using several approaches, and we've found that copying this data fixes the issue. I tried to fix this writting a small utility that we could embed on install, [vim-clip](https://github.com/fmoralesc/vim-clip), but since it uses Gtk ([your comments on the ICCCM](http://lists.slug.org.au/archives/slug-chat/2001/July/msg00054.html) made me approach things from a higher level than xlib), it creates undesired runtime dependencies.

I wanted to ask if it was at all possible to xsel some functionality so we can copy data in this format, and print it out in the same. Just some hints so we could try to hack this up would be appreciated.

**Comment by bfredl** [comment]
@fmoralesc I am currently looking into this. At least copying data using the vimenc format doesn't look _too_ difficult to add (but no promises of quick results)

**Comment by fmoralesc** [comment]
@bfredl cool! The general gist of what to do can be gathered from my utility.

**Comment by bfredl** [comment]
Yes, thanks to your utility code and some looking into `ui.c` in `vim` I `think` I understand what is going on, but we'll see...

**Comment by kfish** [comment]
Hey,

as a keen and loving vim user I'm happy to merge any patches that improve
xsel for this, for example adding support for custom selection types etc.

K.
